repos:
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/PyCQA/isort
    rev: 9.0.0b2
    hooks:
      - id: isort
        language_version: python

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.2
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.0
    hooks:
      - id: mypy
        language_version: python
        exclude: tests/.*
        additional_dependencies:
        - types-cachetools
        - attrs
        - pydantic>=2.4
